name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          default: true
          override: true
          target: thumbv7em-none-eabihf
          components: rustfmt, clippy

    - uses: actions/checkout@v2
    - name: check style
      run: cargo fmt -- --check
    - name: Test
      run: ./tests.sh
